export const LANGUAGES = [
  { code:"en", name:"English", flag:"🇬🇧" },
  { code:"es", name:"Español", flag:"🇪🇸" },
  { code:"fr", name:"Français", flag:"🇫🇷" },
  { code:"pt", name:"Português", flag:"🇧🇷" },
  { code:"ar", name:"العربية", flag:"🇸🇦" },
  { code:"hi", name:"हिन्दी", flag:"🇮🇳" },
  { code:"yo", name:"Yorùbá", flag:"🇳🇬" },
  { code:"zh", name:"中文", flag:"🇨🇳" },
  { code:"de", name:"Deutsch", flag:"🇩🇪" },
  { code:"sw", name:"Kiswahili", flag:"🇰🇪" },
];

type Dict = Record<string, string>;

const T: Record<string, Dict> = {
  en: { discover:"Discover", messages:"Messages", feed:"Feed", friends:"Friends", stories:"Stories", profile:"Profile", explore:"Explore", search:"Search", invite:"Invite", coins:"Coins", video:"Video", settings:"Settings", support:"Help", blocked:"Blocked", views:"Who Viewed", leaderboard:"Leaderboard", verify:"Verify", logout:"Log Out", dark_mode:"Dark Mode", light_mode:"Light Mode", no_profiles:"No profiles yet", no_posts:"No posts yet", no_friends:"No friends yet", send_message:"Type a message...", search_placeholder:"Search by name, username...", like:"Like", comment:"Comment", post:"Post", send:"Send", online:"Online", offline:"Offline", share:"Share with Friends", copy:"Copy", upgrade:"Upgrade", buy_coins:"Buy Coins" },
  es: { discover:"Descubrir", messages:"Mensajes", feed:"Publicaciones", friends:"Amigos", stories:"Historias", profile:"Perfil", explore:"Explorar", search:"Buscar", invite:"Invitar", coins:"Monedas", video:"Video", settings:"Ajustes", support:"Ayuda", blocked:"Bloqueados", views:"Quién vio", leaderboard:"Clasificación", verify:"Verificar", logout:"Cerrar sesión", dark_mode:"Modo oscuro", light_mode:"Modo claro", no_profiles:"No hay perfiles aún", no_posts:"No hay publicaciones", no_friends:"No hay amigos aún", send_message:"Escribe un mensaje...", search_placeholder:"Buscar por nombre...", like:"Me gusta", comment:"Comentar", post:"Publicar", send:"Enviar", online:"En línea", offline:"Desconectado", share:"Compartir con amigos", copy:"Copiar", upgrade:"Mejorar", buy_coins:"Comprar monedas" },
  fr: { discover:"Découvrir", messages:"Messages", feed:"Fil", friends:"Amis", stories:"Stories", profile:"Profil", explore:"Explorer", search:"Chercher", invite:"Inviter", coins:"Pièces", video:"Vidéo", settings:"Paramètres", support:"Aide", blocked:"Bloqués", views:"Qui a vu", leaderboard:"Classement", verify:"Vérifier", logout:"Déconnexion", dark_mode:"Mode sombre", light_mode:"Mode clair", no_profiles:"Pas encore de profils", no_posts:"Pas de publications", no_friends:"Pas encore d'amis", send_message:"Écrire un message...", search_placeholder:"Rechercher par nom...", like:"J'aime", comment:"Commenter", post:"Publier", send:"Envoyer", online:"En ligne", offline:"Hors ligne", share:"Partager avec des amis", copy:"Copier", upgrade:"Améliorer", buy_coins:"Acheter des pièces" },
  pt: { discover:"Descobrir", messages:"Mensagens", feed:"Feed", friends:"Amigos", stories:"Stories", profile:"Perfil", explore:"Explorar", search:"Buscar", invite:"Convidar", coins:"Moedas", video:"Vídeo", settings:"Configurações", support:"Ajuda", blocked:"Bloqueados", views:"Quem viu", leaderboard:"Ranking", verify:"Verificar", logout:"Sair", dark_mode:"Modo escuro", light_mode:"Modo claro", no_profiles:"Nenhum perfil ainda", no_posts:"Nenhum post", no_friends:"Nenhum amigo ainda", send_message:"Digite uma mensagem...", search_placeholder:"Buscar por nome...", like:"Curtir", comment:"Comentar", post:"Postar", send:"Enviar", online:"Online", offline:"Offline", share:"Compartilhar", copy:"Copiar", upgrade:"Melhorar", buy_coins:"Comprar moedas" },
  ar: { discover:"اكتشف", messages:"الرسائل", feed:"المنشورات", friends:"الأصدقاء", stories:"القصص", profile:"الملف الشخصي", explore:"استكشف", search:"بحث", invite:"دعوة", coins:"العملات", video:"فيديو", settings:"الإعدادات", support:"المساعدة", blocked:"المحظورين", views:"من شاهد", leaderboard:"المتصدرين", verify:"التحقق", logout:"تسجيل الخروج", dark_mode:"الوضع الداكن", light_mode:"الوضع الفاتح", no_profiles:"لا توجد ملفات", no_posts:"لا توجد منشورات", no_friends:"لا يوجد أصدقاء", send_message:"اكتب رسالة...", search_placeholder:"ابحث بالاسم...", like:"إعجاب", comment:"تعليق", post:"نشر", send:"إرسال", online:"متصل", offline:"غير متصل", share:"مشاركة", copy:"نسخ", upgrade:"ترقية", buy_coins:"شراء عملات" },
  hi: { discover:"खोजें", messages:"संदेश", feed:"फीड", friends:"दोस्त", stories:"स्टोरीज", profile:"प्रोफाइल", explore:"एक्सप्लोर", search:"खोज", invite:"आमंत्रित", coins:"सिक्के", video:"वीडियो", settings:"सेटिंग्स", support:"सहायता", blocked:"ब्लॉक", views:"किसने देखा", leaderboard:"लीडरबोर्ड", verify:"सत्यापन", logout:"लॉग आउट", dark_mode:"डार्क मोड", light_mode:"लाइट मोड", no_profiles:"कोई प्रोफाइल नहीं", no_posts:"कोई पोस्ट नहीं", no_friends:"कोई दोस्त नहीं", send_message:"संदेश लिखें...", search_placeholder:"नाम से खोजें...", like:"पसंद", comment:"टिप्पणी", post:"पोस्ट", send:"भेजें", online:"ऑनलाइन", offline:"ऑफलाइन", share:"शेयर करें", copy:"कॉपी", upgrade:"अपग्रेड", buy_coins:"सिक्के खरीदें" },
  yo: { discover:"Ṣàwárí", messages:"Ìfiránṣẹ́", feed:"Àwọn ìfiránṣẹ́", friends:"Ọ̀rẹ́", stories:"Ìtàn", profile:"Profaili", explore:"Ṣàwárí", search:"Wá", invite:"Pè", coins:"Owó", video:"Fídíò", settings:"Ètò", support:"Ìrànlọ́wọ́", blocked:"Dínà", views:"Tó wo ẹ", leaderboard:"Àkójọ", verify:"Fìdí múlẹ̀", logout:"Jáde", dark_mode:"Ọ̀nà dúdú", light_mode:"Ọ̀nà funfun", no_profiles:"Kò sí profaili", no_posts:"Kò sí ìfiránṣẹ́", no_friends:"Kò sí ọ̀rẹ́", send_message:"Kọ ìfiránṣẹ́...", search_placeholder:"Wá orúkọ...", like:"Fẹ́ràn", comment:"Sọ̀rọ̀", post:"Fi sílẹ̀", send:"Fi ránṣẹ́", online:"Lórí ayélujára", offline:"Kò sí", share:"Pín", copy:"Daakọ", upgrade:"Gbéga", buy_coins:"Ra owó" },
  zh: { discover:"发现", messages:"消息", feed:"动态", friends:"好友", stories:"故事", profile:"个人资料", explore:"探索", search:"搜索", invite:"邀请", coins:"金币", video:"视频", settings:"设置", support:"帮助", blocked:"已屏蔽", views:"谁看了我", leaderboard:"排行榜", verify:"验证", logout:"退出", dark_mode:"深色模式", light_mode:"浅色模式", no_profiles:"暂无用户", no_posts:"暂无动态", no_friends:"暂无好友", send_message:"输入消息...", search_placeholder:"搜索名字...", like:"喜欢", comment:"评论", post:"发布", send:"发送", online:"在线", offline:"离线", share:"分享", copy:"复制", upgrade:"升级", buy_coins:"购买金币" },
  de: { discover:"Entdecken", messages:"Nachrichten", feed:"Feed", friends:"Freunde", stories:"Stories", profile:"Profil", explore:"Erkunden", search:"Suchen", invite:"Einladen", coins:"Münzen", video:"Video", settings:"Einstellungen", support:"Hilfe", blocked:"Blockiert", views:"Wer hat gesehen", leaderboard:"Rangliste", verify:"Verifizieren", logout:"Abmelden", dark_mode:"Dunkelmodus", light_mode:"Hellmodus", no_profiles:"Keine Profile", no_posts:"Keine Beiträge", no_friends:"Keine Freunde", send_message:"Nachricht eingeben...", search_placeholder:"Nach Name suchen...", like:"Gefällt mir", comment:"Kommentar", post:"Posten", send:"Senden", online:"Online", offline:"Offline", share:"Teilen", copy:"Kopieren", upgrade:"Upgrade", buy_coins:"Münzen kaufen" },
  sw: { discover:"Gundua", messages:"Ujumbe", feed:"Machapisho", friends:"Marafiki", stories:"Hadithi", profile:"Wasifu", explore:"Chunguza", search:"Tafuta", invite:"Alika", coins:"Sarafu", video:"Video", settings:"Mipangilio", support:"Msaada", blocked:"Waliozuiwa", views:"Aliyeangalia", leaderboard:"Orodha", verify:"Thibitisha", logout:"Ondoka", dark_mode:"Hali ya giza", light_mode:"Hali ya mwanga", no_profiles:"Hakuna wasifu", no_posts:"Hakuna machapisho", no_friends:"Hakuna marafiki", send_message:"Andika ujumbe...", search_placeholder:"Tafuta jina...", like:"Penda", comment:"Maoni", post:"Chapisha", send:"Tuma", online:"Mtandaoni", offline:"Nje ya mtandao", share:"Shiriki", copy:"Nakili", upgrade:"Boresha", buy_coins:"Nunua sarafu" },
};

export function t(lang: string, key: string): string {
  return T[lang]?.[key] || T.en[key] || key;
}
