ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "hidePhone" BOOLEAN DEFAULT true;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "hideEmail" BOOLEAN DEFAULT true;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "hideDob" BOOLEAN DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "dateOfBirth" TIMESTAMP;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "referredBy" TEXT;
