"use client";
import { useState, useRef, useEffect } from "react";
import { useUser } from "../layout";
import { Camera, CheckCircle, XCircle, RotateCcw, Shield, Upload, ArrowLeft, X, Sparkles } from "lucide-react";
import Link from "next/link";
type Phase = "intro"|"id_select"|"id_upload"|"prep"|"live"|"processing"|"success"|"failed";
interface Step { id:string; text:string; arrow:string; ms:number; }
const IDS = [{v:"passport",l:"International Passport",i:"\u{1F6C2}"},{v:"national_id",l:"National ID Card",i:"\u{1FAAA}"},{v:"drivers_license",l:"Driver License",i:"\u{1F697}"},{v:"voters_card",l:"Voter Card",i:"\u{1F5F3}"},{v:"residence_permit",l:"Residence Permit",i:"\u{1F3E0}"},{v:"military_id",l:"Military ID",i:"\u{1F396}"}];
const B:Step[] = [{id:"center",text:"Look straight ahead",arrow:"",ms:4000},{id:"left",text:"Turn to the left",arrow:"left",ms:4000},{id:"right",text:"Turn to the right",arrow:"right",ms:4000}];
const F:Step[] = [{id:"blink",text:"Blink your eyes",arrow:"",ms:4000},{id:"smile",text:"Smile",arrow:"",ms:4000}];
function Live({steps,stream,onDone,onCancel}:{steps:Step[];stream:MediaStream;onDone:(f:string[])=>void;onCancel:()=>void}){
  const vRef=useRef<HTMLVideoElement>(null),cRef=useRef<HTMLCanvasElement>(null);
  const [si,setSi]=useState(0),[pct,setPct]=useState(0);
  const caps=useRef<string[]>([]),done=useRef(false),tmr=useRef<any>(null);
  function snap(){const v=vRef.current,c=cRef.current;if(!v||!c||!v.videoWidth)return"";c.width=480;c.height=480;const x=c.getContext("2d");if(!x)return"";const s=Math.min(v.videoWidth,v.videoHeight);x.drawImage(v,(v.videoWidth-s)/2,(v.videoHeight-s)/2,s,s,0,0,480,480);return c.toDataURL("image/jpeg",0.8);}
  useEffect(()=>{const v=vRef.current;if(v&&stream){v.srcObject=stream;v.play().catch(()=>{});}return()=>{if(tmr.current)clearInterval(tmr.current);};},[]);
  useEffect(()=>{if(done.current||si>=steps.length)return;setPct(0);const start=Date.now(),dur=steps[si].ms;if(tmr.current)clearInterval(tmr.current);tmr.current=setInterval(()=>{const e=Date.now()-start,p=Math.min(100,(e/dur)*100);setPct(p);if(e>=dur){clearInterval(tmr.current);tmr.current=null;const f=snap();if(f)caps.current.push(f);if(si+1>=steps.length){done.current=true;onDone(caps.current);}else{setSi(si+1);}}},60);return()=>{if(tmr.current)clearInterval(tmr.current);};},[si]);
  const step=steps[si]||steps[0];
  return(<div className="fixed inset-0 z-[100] bg-white flex flex-col"><canvas ref={cRef} className="hidden"/><div className="flex items-center justify-between px-4 pt-12 pb-3"><button onClick={onCancel} className="w-10 h-10 flex items-center justify-center"><X className="w-6 h-6 text-gray-900"/></button><span className="text-sm font-medium text-gray-500">{si+1}/{steps.length}</span><span className="w-10"/></div><div className="flex-1 flex flex-col items-center justify-center px-6"><div className="relative" style={{width:320,height:320}}><svg className="absolute inset-0 w-full h-full" viewBox="0 0 320 320" style={{transform:"rotate(-90deg)"}}><circle cx="160" cy="160" r={153} fill="none" stroke="#d1d5db" strokeWidth="7"/><circle cx="160" cy="160" r={153} fill="none" stroke="#2563eb" strokeWidth="7" strokeLinecap="round" strokeDasharray={2*Math.PI*153} strokeDashoffset={2*Math.PI*153*(1-pct/100)} style={{transition:"stroke-dashoffset 0.1s linear"}}/></svg><div className="absolute rounded-full overflow-hidden" style={{top:7,left:7,right:7,bottom:7}}><video ref={vRef} className="w-full h-full object-cover" playsInline muted autoPlay style={{transform:"scaleX(-1)"}}/></div>{step.arrow==="left"&&<div className="absolute left-[-24px] top-1/2 -translate-y-1/2 w-12 h-12 bg-blue-600 rounded-full flex items-center justify-center shadow-lg z-10"><ArrowLeft className="w-6 h-6 text-white"/></div>}{step.arrow==="right"&&<div className="absolute right-[-24px] top-1/2 -translate-y-1/2 w-12 h-12 bg-blue-600 rounded-full flex items-center justify-center shadow-lg z-10 rotate-180"><ArrowLeft className="w-6 h-6 text-white"/></div>}</div><h2 className="text-2xl font-bold text-gray-900 mt-10 text-center">{step.text}</h2><p className="text-sm mt-2 text-green-600 font-medium">{pct<30?"Get ready...":pct<90?"Hold still...":"Almost done..."}</p></div><div className="px-6 pb-10"><div className="flex items-center justify-center gap-2">{steps.map((_,i)=>(<div key={i} className="h-2 rounded-full" style={{width:i===si?24:8,backgroundColor:i<=si?"#2563eb":"#d1d5db",transition:"all 0.3s"}}/>))}</div></div></div>);
}
export default function VerifyPage(){
  const{user,reload,dark}=useUser();const dc=dark;const sRef=useRef<MediaStream|null>(null);
  const[phase,setPhase]=useState<Phase>("intro");const[steps,setSteps]=useState<Step[]>([...B,F[0]]);const[frames,setFrames]=useState<string[]>([]);
  const[idt,setIdt]=useState("");const[idf,setIdf]=useState<string|null>(null);const[idb,setIdb]=useState<string|null>(null);const[err,setErr]=useState("");
  const fr1=useRef<HTMLInputElement>(null),fr2=useRef<HTMLInputElement>(null);
  const stopC=()=>{if(sRef.current){sRef.current.getTracks().forEach(t=>t.stop());sRef.current=null;}};
  useEffect(()=>()=>stopC(),[]);
  const startC=async()=>{setErr("");try{const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:"user",width:{ideal:640},height:{ideal:640}},audio:false});sRef.current=s;setSteps([...B,F[Math.random()<0.5?0:1]]);setFrames([]);setPhase("live");}catch{setErr("Camera access required.");}};
  const onDone=(f:string[])=>{setFrames(f);stopC();setPhase("processing");};
  const onCancel=()=>{stopC();setPhase("prep");};
  useEffect(()=>{if(phase!=="processing")return;let d=false;(async()=>{await new Promise(r=>setTimeout(r,500));if(d)return;try{const r=await fetch("/api/auth/verify",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({verificationPhoto:frames[0]||"",idDocument:idf||"",idDocumentBack:idb||"",idType:idt,frames:frames.length,selfieFrames:frames,challenges:steps.map(s=>s.id)})});if(d)return;const j=await r.json();if(r.ok){setPhase("success");reload();}else{setPhase("failed");setErr(j.error||"Failed.");}}catch{if(!d){setPhase("failed");setErr("Connection error.");}}})();return()=>{d=true;};},[phase]);
  const upF=(e:React.ChangeEvent<HTMLInputElement>,s:"f"|"b")=>{const f=e.target.files?.[0];if(!f)return;if(f.size>10*1024*1024){setErr("Max 10MB");return;}setErr("");const r=new FileReader();r.onload=v=>{if(s==="f")setIdf(v.target?.result as string);else setIdb(v.target?.result as string);};r.readAsDataURL(f);};
  const retry=()=>{stopC();setPhase("intro");setErr("");setIdf(null);setIdb(null);setIdt("");setFrames([]);};
  if(!user)return null;
  if(user.verified||user.verificationStatus==="approved")return(<div className="max-w-md mx-auto text-center py-16"><div className={"rounded-3xl border p-8 "+(dc?"bg-gray-800 border-gray-700":"bg-white border-gray-100 shadow-xl")}><div className="w-24 h-24 mx-auto bg-emerald-100 rounded-full flex items-center justify-center mb-5"><CheckCircle className="w-12 h-12 text-emerald-500"/></div><h2 className={"text-2xl font-extrabold mb-2 "+(dc?"text-white":"text-gray-900")}>Verified!</h2><p className={"text-sm mb-6 "+(dc?"text-gray-400":"text-gray-500")}>Your identity is confirmed.</p><Link href="/dashboard/profile" className="px-6 py-3 bg-gradient-to-r from-emerald-500 to-teal-500 text-white rounded-full font-bold text-sm">View Profile</Link></div></div>);
  if(user.verificationStatus==="pending")return(<div className="max-w-md mx-auto text-center py-16"><div className={"rounded-3xl border p-8 "+(dc?"bg-gray-800 border-gray-700":"bg-white border-gray-100 shadow-xl")}><div className="w-24 h-24 mx-auto bg-amber-100 rounded-full flex items-center justify-center mb-5"><div className="w-10 h-10 border-4 border-amber-500 border-t-transparent rounded-full animate-spin"/></div><h2 className={"text-2xl font-extrabold mb-2 "+(dc?"text-white":"text-gray-900")}>Under Review</h2><p className={"text-sm mb-6 "+(dc?"text-gray-400":"text-gray-500")}>Usually 1-24 hours.</p><Link href="/dashboard" className="px-6 py-3 bg-gradient-to-r from-rose-500 to-pink-500 text-white rounded-full font-bold text-sm">Dashboard</Link></div></div>);
  return(<div className="max-w-lg mx-auto">
    {phase==="live"&&sRef.current&&<Live steps={steps} stream={sRef.current} onDone={onDone} onCancel={onCancel}/>}
    {phase==="intro"&&(<div className="py-4"><div className={"rounded-3xl overflow-hidden border "+(dc?"bg-gray-800 border-gray-700":"bg-white border-gray-100 shadow-xl")}><div className="bg-gradient-to-br from-blue-600 via-indigo-600 to-purple-700 p-8 text-center"><div className="w-20 h-20 mx-auto bg-white/10 backdrop-blur rounded-2xl flex items-center justify-center mb-4"><Shield className="w-10 h-10 text-white"/></div><h1 className="text-2xl font-extrabold text-white mb-2">Identity Verification</h1><p className="text-blue-200 text-sm">Get the trusted badge</p></div><div className="p-6"><div className={"p-4 rounded-xl mb-6 "+(dc?"bg-emerald-500/10 border border-emerald-500/20":"bg-emerald-50 border border-emerald-100")}><p className={"text-xs font-medium flex items-center gap-2 "+(dc?"text-emerald-400":"text-emerald-700")}><Sparkles className="w-4 h-4"/>Earn 100 coins when verified!</p></div><button onClick={()=>setPhase("id_select")} className="w-full py-4 bg-gradient-to-r from-blue-600 to-purple-600 text-white rounded-2xl font-bold">Begin Verification</button></div></div></div>)}
    {phase==="id_select"&&(<div className="py-4"><div className={"rounded-3xl border p-6 "+(dc?"bg-gray-800 border-gray-700":"bg-white border-gray-100 shadow-xl")}><div className="flex items-center gap-3 mb-6"><button onClick={()=>setPhase("intro")} className="p-2 rounded-xl hover:bg-gray-100"><ArrowLeft className="w-5 h-5"/></button><h2 className={"text-xl font-extrabold "+(dc?"text-white":"text-gray-900")}>Select ID Type</h2></div><div className="space-y-2">{IDS.map(t=>(<button key={t.v} onClick={()=>{setIdt(t.v);setPhase("id_upload");}} className={"w-full flex items-center gap-4 p-4 rounded-2xl border text-left "+(dc?"border-gray-700 hover:border-blue-500":"border-gray-200 hover:border-blue-300")}><span className="text-3xl">{t.i}</span><span className={"font-semibold text-sm "+(dc?"text-white":"text-gray-900")}>{t.l}</span></button>))}</div></div></div>)}
    {phase==="id_upload"&&(<div className="py-4"><div className={"rounded-3xl border p-6 "+(dc?"bg-gray-800 border-gray-700":"bg-white border-gray-100 shadow-xl")}><div className="flex items-center gap-3 mb-6"><button onClick={()=>setPhase("id_select")} className="p-2 rounded-xl hover:bg-gray-100"><ArrowLeft className="w-5 h-5"/></button><h2 className={"text-xl font-extrabold "+(dc?"text-white":"text-gray-900")}>Upload ID</h2></div>{err&&<div className="mb-4 p-3 bg-red-50 border border-red-200 rounded-xl text-red-600 text-sm">{err}</div>}<input ref={fr1} type="file" accept="image/*" capture="environment" onChange={e=>upF(e,"f")} className="hidden"/><input ref={fr2} type="file" accept="image/*" capture="environment" onChange={e=>upF(e,"b")} className="hidden"/><p className={"text-sm font-semibold mb-2 "+(dc?"text-gray-300":"text-gray-700")}>Front *</p>{idf?(<div className="relative mb-4"><img src={idf} className="w-full rounded-2xl border object-cover max-h-48"/><button onClick={()=>setIdf(null)} className="absolute top-2 right-2 w-8 h-8 bg-red-500 text-white rounded-full flex items-center justify-center"><X className="w-4 h-4"/></button></div>):(<button onClick={()=>fr1.current?.click()} className="w-full py-10 rounded-2xl border-2 border-dashed flex flex-col items-center gap-2 mb-4 text-gray-400 hover:border-blue-400"><Upload className="w-8 h-8"/><p className="text-sm font-semibold">Upload front</p></button>)}<p className={"text-sm font-semibold mb-2 "+(dc?"text-gray-300":"text-gray-700")}>Back (optional)</p>{idb?(<div className="relative mb-4"><img src={idb} className="w-full rounded-2xl border object-cover max-h-48"/><button onClick={()=>setIdb(null)} className="absolute top-2 right-2 w-8 h-8 bg-red-500 text-white rounded-full flex items-center justify-center"><X className="w-4 h-4"/></button></div>):(<button onClick={()=>fr2.current?.click()} className="w-full py-8 rounded-2xl border-2 border-dashed flex flex-col items-center gap-2 mb-4 text-gray-400"><Upload className="w-6 h-6"/><p className="text-xs">Upload back</p></button>)}<div className="flex gap-3 mt-4"><button onClick={()=>setPhase("id_select")} className={"flex-1 py-3 rounded-xl border-2 font-bold text-sm "+(dc?"border-gray-600 text-gray-300":"border-gray-200 text-gray-600")}>Back</button><button onClick={()=>{if(!idf){setErr("Upload front of ID");return;}setPhase("prep");}} className="flex-1 py-3 bg-gradient-to-r from-blue-600 to-purple-600 text-white rounded-xl font-bold text-sm">Next</button></div></div></div>)}
    {phase==="prep"&&(<div className="py-4"><div className={"rounded-3xl border p-6 "+(dc?"bg-gray-800 border-gray-700":"bg-white border-gray-100 shadow-xl")}><div className="flex items-center gap-3 mb-6"><button onClick={()=>setPhase("id_upload")} className="p-2 rounded-xl hover:bg-gray-100"><ArrowLeft className="w-5 h-5"/></button><h2 className={"text-xl font-extrabold "+(dc?"text-white":"text-gray-900")}>Live Face Scan</h2></div><div className={"rounded-2xl p-5 mb-6 "+(dc?"bg-blue-500/10":"bg-blue-50")}><p className={"text-sm font-bold mb-3 "+(dc?"text-white":"text-gray-900")}>Steps:</p><div className="space-y-2">{["Look straight ahead","Turn left","Turn right","Random: blink or smile"].map((t,i)=>(<div key={i} className="flex items-center gap-3"><div className={"w-7 h-7 rounded-full flex items-center justify-center text-xs font-bold "+(dc?"bg-gray-700 text-gray-300":"bg-white text-gray-600 shadow-sm")}>{i+1}</div><span className={"text-sm "+(dc?"text-gray-300":"text-gray-700")}>{t}</span></div>))}</div></div><p className={"text-xs mb-6 "+(dc?"text-amber-400":"text-amber-700")}>Each step has 4 seconds. Follow the instruction while the blue ring fills. Remove hats and sunglasses.</p>{err&&<div className="mb-4 p-3 bg-red-50 border border-red-200 rounded-xl text-red-600 text-sm">{err}</div>}<button onClick={startC} className="w-full py-4 bg-gradient-to-r from-blue-600 to-purple-600 text-white rounded-2xl font-bold flex items-center justify-center gap-2"><Camera className="w-5 h-5"/>Start Face Scan</button></div></div>)}
    {phase==="processing"&&(<div className="text-center py-16"><div className="w-16 h-16 mx-auto border-4 border-blue-200 border-t-blue-600 rounded-full animate-spin mb-6"/><h2 className={"text-xl font-extrabold mb-2 "+(dc?"text-white":"text-gray-900")}>Analyzing...</h2><p className={"text-sm "+(dc?"text-gray-400":"text-gray-500")}>Verifying your documents</p></div>)}
    {phase==="success"&&(<div className="text-center py-8"><div className={"rounded-3xl border p-8 "+(dc?"bg-gray-800 border-gray-700":"bg-white border-gray-100 shadow-xl")}><div className="w-24 h-24 mx-auto bg-emerald-100 rounded-full flex items-center justify-center mb-6"><CheckCircle className="w-12 h-12 text-emerald-500"/></div><h2 className={"text-2xl font-extrabold mb-2 "+(dc?"text-white":"text-gray-900")}>Submitted!</h2><p className={"text-sm mb-6 "+(dc?"text-gray-400":"text-gray-500")}>Review within 24 hours.</p><Link href="/dashboard" className="inline-block px-8 py-3 bg-gradient-to-r from-emerald-500 to-teal-500 text-white rounded-full font-bold">Dashboard</Link></div></div>)}
    {phase==="failed"&&(<div className="text-center py-8"><div className={"rounded-3xl border p-8 "+(dc?"bg-gray-800 border-gray-700":"bg-white border-gray-100 shadow-xl")}><div className="w-24 h-24 mx-auto bg-red-100 rounded-full flex items-center justify-center mb-6"><XCircle className="w-12 h-12 text-red-500"/></div><h2 className={"text-2xl font-extrabold mb-2 "+(dc?"text-white":"text-gray-900")}>Failed</h2><p className={"text-sm mb-6 "+(dc?"text-gray-400":"text-gray-500")}>{err||"Could not verify."}</p><button onClick={retry} className="inline-flex items-center gap-2 px-8 py-3 bg-gradient-to-r from-rose-500 to-pink-500 text-white rounded-full font-bold"><RotateCcw className="w-4 h-4"/>Try Again</button></div></div>)}
  </div>);
}
